// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBikx8ha4__XCEcTWJpHZSDOwpBDxEHOfE',
    appId: '1:265290167508:web:bcd195767352dbb57eb741',
    messagingSenderId: '265290167508',
    projectId: 'coffee-shop-cf61f',
    authDomain: 'coffee-shop-cf61f.firebaseapp.com',
    storageBucket: 'coffee-shop-cf61f.appspot.com',
    measurementId: 'G-YBHJR4D4E3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACbbpGmGHalP_xMJefsk3ixPLnQVnVcIs',
    appId: '1:265290167508:android:e4e6e851be5746247eb741',
    messagingSenderId: '265290167508',
    projectId: 'coffee-shop-cf61f',
    storageBucket: 'coffee-shop-cf61f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlGPcbVjxi9RHpoOdKJluvahP-IuMBxrg',
    appId: '1:265290167508:ios:487d65feea6830027eb741',
    messagingSenderId: '265290167508',
    projectId: 'coffee-shop-cf61f',
    storageBucket: 'coffee-shop-cf61f.appspot.com',
    iosBundleId: 'com.example.myCoffeeHouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlGPcbVjxi9RHpoOdKJluvahP-IuMBxrg',
    appId: '1:265290167508:ios:487d65feea6830027eb741',
    messagingSenderId: '265290167508',
    projectId: 'coffee-shop-cf61f',
    storageBucket: 'coffee-shop-cf61f.appspot.com',
    iosBundleId: 'com.example.myCoffeeHouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBikx8ha4__XCEcTWJpHZSDOwpBDxEHOfE',
    appId: '1:265290167508:web:56e27d4a0346418b7eb741',
    messagingSenderId: '265290167508',
    projectId: 'coffee-shop-cf61f',
    authDomain: 'coffee-shop-cf61f.firebaseapp.com',
    storageBucket: 'coffee-shop-cf61f.appspot.com',
    measurementId: 'G-6KYNWVFEBD',
  );
}
